# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canoncical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# The program to use to edit the cache.
CMAKE_EDIT_COMMAND = /usr/bin/ccmake

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/collab/xhzhu/Study/HardiToolbox

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/collab/xhzhu/Study/HardiToolbox

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/collab/xhzhu/Study/HardiToolbox/CMakeFiles /home/collab/xhzhu/Study/HardiToolbox/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/collab/xhzhu/Study/HardiToolbox/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named HardiToolbox

# Build rule for target.
HardiToolbox: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 HardiToolbox
.PHONY : HardiToolbox

# fast build rule for target.
HardiToolbox/fast:
	$(MAKE) -f CMakeFiles/HardiToolbox.dir/build.make CMakeFiles/HardiToolbox.dir/build
.PHONY : HardiToolbox/fast

#=============================================================================
# Target rules for targets named RunMultiTensorTest

# Build rule for target.
RunMultiTensorTest: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 RunMultiTensorTest
.PHONY : RunMultiTensorTest

# fast build rule for target.
RunMultiTensorTest/fast:
	$(MAKE) -f CMakeFiles/RunMultiTensorTest.dir/build.make CMakeFiles/RunMultiTensorTest.dir/build
.PHONY : RunMultiTensorTest/fast

HardiToolbox.o: HardiToolbox.cpp.o
.PHONY : HardiToolbox.o

# target to build an object file
HardiToolbox.cpp.o:
	$(MAKE) -f CMakeFiles/HardiToolbox.dir/build.make CMakeFiles/HardiToolbox.dir/HardiToolbox.cpp.o
	$(MAKE) -f CMakeFiles/RunMultiTensorTest.dir/build.make CMakeFiles/RunMultiTensorTest.dir/HardiToolbox.cpp.o
.PHONY : HardiToolbox.cpp.o

HardiToolbox.i: HardiToolbox.cpp.i
.PHONY : HardiToolbox.i

# target to preprocess a source file
HardiToolbox.cpp.i:
	$(MAKE) -f CMakeFiles/HardiToolbox.dir/build.make CMakeFiles/HardiToolbox.dir/HardiToolbox.cpp.i
	$(MAKE) -f CMakeFiles/RunMultiTensorTest.dir/build.make CMakeFiles/RunMultiTensorTest.dir/HardiToolbox.cpp.i
.PHONY : HardiToolbox.cpp.i

HardiToolbox.s: HardiToolbox.cpp.s
.PHONY : HardiToolbox.s

# target to generate assembly for a file
HardiToolbox.cpp.s:
	$(MAKE) -f CMakeFiles/HardiToolbox.dir/build.make CMakeFiles/HardiToolbox.dir/HardiToolbox.cpp.s
	$(MAKE) -f CMakeFiles/RunMultiTensorTest.dir/build.make CMakeFiles/RunMultiTensorTest.dir/HardiToolbox.cpp.s
.PHONY : HardiToolbox.cpp.s

main.o: main.cpp.o
.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) -f CMakeFiles/HardiToolbox.dir/build.make CMakeFiles/HardiToolbox.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i
.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/HardiToolbox.dir/build.make CMakeFiles/HardiToolbox.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s
.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/HardiToolbox.dir/build.make CMakeFiles/HardiToolbox.dir/main.cpp.s
.PHONY : main.cpp.s

testMultiTensor.o: testMultiTensor.cpp.o
.PHONY : testMultiTensor.o

# target to build an object file
testMultiTensor.cpp.o:
	$(MAKE) -f CMakeFiles/RunMultiTensorTest.dir/build.make CMakeFiles/RunMultiTensorTest.dir/testMultiTensor.cpp.o
.PHONY : testMultiTensor.cpp.o

testMultiTensor.i: testMultiTensor.cpp.i
.PHONY : testMultiTensor.i

# target to preprocess a source file
testMultiTensor.cpp.i:
	$(MAKE) -f CMakeFiles/RunMultiTensorTest.dir/build.make CMakeFiles/RunMultiTensorTest.dir/testMultiTensor.cpp.i
.PHONY : testMultiTensor.cpp.i

testMultiTensor.s: testMultiTensor.cpp.s
.PHONY : testMultiTensor.s

# target to generate assembly for a file
testMultiTensor.cpp.s:
	$(MAKE) -f CMakeFiles/RunMultiTensorTest.dir/build.make CMakeFiles/RunMultiTensorTest.dir/testMultiTensor.cpp.s
.PHONY : testMultiTensor.cpp.s

testProc.o: testProc.cpp.o
.PHONY : testProc.o

# target to build an object file
testProc.cpp.o:
	$(MAKE) -f CMakeFiles/HardiToolbox.dir/build.make CMakeFiles/HardiToolbox.dir/testProc.cpp.o
.PHONY : testProc.cpp.o

testProc.i: testProc.cpp.i
.PHONY : testProc.i

# target to preprocess a source file
testProc.cpp.i:
	$(MAKE) -f CMakeFiles/HardiToolbox.dir/build.make CMakeFiles/HardiToolbox.dir/testProc.cpp.i
.PHONY : testProc.cpp.i

testProc.s: testProc.cpp.s
.PHONY : testProc.s

# target to generate assembly for a file
testProc.cpp.s:
	$(MAKE) -f CMakeFiles/HardiToolbox.dir/build.make CMakeFiles/HardiToolbox.dir/testProc.cpp.s
.PHONY : testProc.cpp.s

utils.o: utils.cpp.o
.PHONY : utils.o

# target to build an object file
utils.cpp.o:
	$(MAKE) -f CMakeFiles/HardiToolbox.dir/build.make CMakeFiles/HardiToolbox.dir/utils.cpp.o
.PHONY : utils.cpp.o

utils.i: utils.cpp.i
.PHONY : utils.i

# target to preprocess a source file
utils.cpp.i:
	$(MAKE) -f CMakeFiles/HardiToolbox.dir/build.make CMakeFiles/HardiToolbox.dir/utils.cpp.i
.PHONY : utils.cpp.i

utils.s: utils.cpp.s
.PHONY : utils.s

# target to generate assembly for a file
utils.cpp.s:
	$(MAKE) -f CMakeFiles/HardiToolbox.dir/build.make CMakeFiles/HardiToolbox.dir/utils.cpp.s
.PHONY : utils.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... HardiToolbox"
	@echo "... RunMultiTensorTest"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... HardiToolbox.o"
	@echo "... HardiToolbox.i"
	@echo "... HardiToolbox.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... testMultiTensor.o"
	@echo "... testMultiTensor.i"
	@echo "... testMultiTensor.s"
	@echo "... testProc.o"
	@echo "... testProc.i"
	@echo "... testProc.s"
	@echo "... utils.o"
	@echo "... utils.i"
	@echo "... utils.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

